services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cc
      POSTGRES_USER: cc
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cc"]
      interval: 5s
      timeout: 3s
      retries: 20
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  pgdata: {}
