name: Codex CI / backend-tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('backend/requirements-dev.txt') }}
      - name: Install
        run: |
          python -m pip install -U pip
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip freeze
      - name: Lint (ruff minimal)
        run: |
          python - <<'PY'
print('skip ruff for step-01 (optional)')
PY
      - name: Tests + coverage
        env:
          PYTHONDONTWRITEBYTECODE: '1'
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=app --cov-report=xml
          test -f coverage.xml && echo "coverage.xml generated" || (echo "coverage.xml missing" && exit 1)
      - name: Coverage gate >= 70%
        run: |
          python - <<'PY'
import xml.etree.ElementTree as ET, sys
r = ET.parse('coverage.xml').getroot()
rate = float(r.get('line-rate')) * 100
print(f"Coverage: {rate:.2f}%")
sys.exit(0 if rate >= 70.0 else 1)
PY
