name: docs-guard
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  docs-guard:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Export specs (ensure up-to-date)
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          Set-StrictMode -Version Latest
          ./PS1/specs/export_employe.ps1
          ./PS1/specs/export_org.ps1
          ./PS1/specs/export_rbac.ps1
          ./PS1/specs/export_auth.ps1
          ./PS1/specs/export_settings.ps1
          ./PS1/specs/export_notifications.ps1
          ./PS1/specs/export_i18n.ps1
          ./PS1/specs/export_custom_fields.ps1
          ./PS1/specs/export_import.ps1
          ./PS1/specs/export_audit.ps1
      - name: Run docs guard
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          Set-StrictMode -Version Latest
          ./PS1/tools/docs_guard.ps1
