name: Codex CI / guards
on: [pull_request]
jobs:
  guards:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run guards
        shell: pwsh
        run: ./tools/guards/run_all_guards.ps1
        env:
          PR_BODY: ${{ github.event.pull_request.body || '' }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
