name: your-workflow
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Check pwsh version
        shell: pwsh
        run: pwsh -v

      - name: Run init script
        shell: pwsh
        run: ./PS1/init_repo.ps1 -Verbose
