name: your-workflow
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PowerShell 7
        uses: PowerShell/setup-pwsh@v2
        with:
          pwsh-version: '7.4.x'

      - name: Run PS script
        shell: pwsh
        run: ./PS1/init_repo.ps1 -Verbose
